Add `pressF4` and `pressF1` methods to GridView and TextField
robocorp/rpaframework pull request #1130
Opened 2023-11-13 15:08 UTC by wisenrico

These two methods are missing on the SapGUILibrary.

2023-11-13 15:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/robocorp/rpaframework?pullRequest=1130) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/robocorp/rpaframework?pullRequest=1130) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/robocorp/rpaframework?pullRequest=1130) it.</sub>

2023-11-13 15:38 UTC, mikahanninen requested changes

2023-11-13 15:38 UTC, mikahanninen commented on packages/main/src/RPA/SAP.py
> +    def press_f1(self, element_id):
Can you add the type into the method parameters ? `element_id: str`

2023-11-13 15:38 UTC, mikahanninen commented on packages/main/src/RPA/SAP.py
> +        :param element: SAP element
param `element` needs to match the parameter name which is `element_id`

2023-11-13 15:39 UTC, mikahanninen commented
Hi @wisenrico! Thank you for the contribution ❤️ I added couple of comments.

2023-11-13 15:48 UTC, wisenrico commented
I have addressed the comments 👍🏻

2023-11-14 07:35 UTC, mikahanninen commented
You also need to accept the Github's [CLA](https://cla-assistant.io/robocorp/rpaframework?pullRequest=1130).

2023-11-14 11:21 UTC, mikahanninen approved these changes

2023-11-14 13:34 UTC, merged