Use ROBOCORP_BROWSERS env variable to determine default browsers
robocorp/rpaframework pull request #780
Opened 2023-01-23 11:06 UTC by avaissi

* ROBOCORP_BROWSERS env variable, if available, is used to determine default browsers
* ROBOCORP_BROWSERS env is re-checked each time Open Available Browser is called

2023-01-23 11:11 UTC, avaissi commented
The reasoning behind the PR is give control for user to determine the order default browsers are tried

2023-01-23 11:37 UTC, cmin764 reviewed
This looks good in general! An additional improvement would be to move the browser preference out of the _core_ package entirely.

Is this old `DRIVER_PREFERENCE` used in any other place apart from `RPA.Browser.Selenium`? If not, then maybe it would be best to move this logic near the library itself in _main_. What do you think?

2023-01-23 12:26 UTC, avaissi commented
> This looks good in general! An additional improvement would be to move the browser preference function out of the _core_ package entirely, into _main_.
> 
> Is this old `DRIVER_PREFERENCE` constant used in any other place apart from `RPA.Browser.Selenium`? If not, then maybe it would be best to move this logic near the library itself in _main_ (so we don't depend on _core_ updates for such behaviour). What do you think?
> 
> Newly created [Issue](https://github.com/robocorp/rpaframework/issues/781) from [epic](https://github.com/robocorp/rpaframework/issues/720)

This sounds good to me. Less dependencies the better 👍 I'll update the PR along with possible variable name change

2023-01-25 08:51 UTC, cmin764 requested changes
This looks better now!

Further required changes (which I guess they are already WIP since this PR is still marked as draft):
1. Bump the major.minor.**hotfix** version of _core_, even if it looks like a breaking change, since only _main_ depends on this change and is already made independent of it in this PR.
2. Bump the hotfix version as well of _main_.
3. Add release note into for main into _docs/source/releasenotes.rst_.
4. You can merge.

### Post-merge
1. Release _core_ from master.
2. Poetry update _main_ (to use latest just released _core_) and release _main_.
3. Release published with releasenotes.io and Slack announcement channels. (with release notes taken from rpaframework.org)

2023-01-25 10:39 UTC, cmin764 approved these changes
LGTM! (left some nits)

2023-01-25 10:39 UTC, cmin764 commented on docs/source/releasenotes.rst
> +  default search order of browsers, when using the ``Open Available Browser``-keyword
```suggestion
  default search order of browsers, when using the ``Open Available Browser`` keyword.
```

maybe?

2023-01-25 10:39 UTC, cmin764 commented on packages/main/src/RPA/Browser/Selenium.py
> +                for browser in os.getenv("RPA_SELENIUM_BROWSER_ORDER", "").split(sep=",")
```suggestion
                for browser in browsers.split(sep=",")
```
DRY

2023-01-25 12:29 UTC, merged