Locators syntax parser (draft)
robocorp/rpaframework pull request #99
Opened 2020-12-04 13:21 UTC by osrjv

Needs a bit more tests and some new locators types, but syntax parser works with desktop. And a bunch of documentation too.

2020-12-07 10:17 UTC, xylix requested changes

2020-12-07 10:23 UTC, osrjv commented on packages/core/src/RPA/core/geometry.py
> +        if isinstance(element, Undefined):
Maybe it should not be supported at all for the operation. It was mainly for compatibility for the one existing call-site, but might as well make the check there

2020-12-07 10:23 UTC, osrjv commented on packages/core/src/RPA/core/locators/literal.py
> +def parse(locator: str) -> Locator:
:heavy_check_mark:

2020-12-07 10:24 UTC, osrjv commented on packages/core/src/RPA/core/locators/literal.py
> +        name, _, value = str(locator).partition(":")
partition() splits on the first occurrence, so any paths should be left untouched

2020-12-07 10:36 UTC, osrjv commented on packages/core/src/RPA/core/locators/literal.py
> +    if name == "alias":
The variables are named a bit confusingly here. In this function `name` is the type of locator, e.g. `alias` or `image`, and `value` is well.. the value for it. Including the "name" for the alias. Due to how partition works, we would anyways have to somehow check if we want to pass `name` or `value` into the loader.

2020-12-07 10:43 UTC, osrjv commented on packages/core/src/RPA/core/locators/syntax.py
> +NAMES = {
Probably not. We could use that and just pretty print using with `token.value`, I think?

2020-12-07 10:47 UTC, osrjv commented on packages/core/src/RPA/core/locators/syntax.py
> +ValueType = Union[Locator, "Not", "Expression", "Chain"]
It at least _seems_ to be working in 3.7 and I didn't find any mention of it in docs. There was a note about `typing.Literal` being a Python 3.8 feature, but that's a union of actual string literals (https://docs.python.org/3/library/typing.html#typing.Literal)

2020-12-07 12:34 UTC, xylix commented on packages/core/src/RPA/core/locators/syntax.py
> +ValueType = Union[Locator, "Not", "Expression", "Chain"]
Oh right these are lazy references to real classes. Then it is a-ok

2020-12-07 12:36 UTC, xylix commented on packages/core/src/RPA/core/locators/syntax.py
> +NAMES = {
Yeah I think that would work well. I guess only downside is that if I have understood correctly, doing Enum unions with "string enums" can be harder than with Int enums if that's something we want.

2020-12-07 12:38 UTC, xylix commented on packages/core/src/RPA/core/geometry.py
> +        if isinstance(element, Undefined):
Yeah at least based on the type signature it doesn't make sense to accept Undefined, since it is not a Region.

2020-12-08 13:54 UTC, osrjv commented
Commits cherry-picked individually to master

2020-12-08 13:54 UTC, closed without merging